// WITHDRAWAL ACTION TYPES
export const WITHDRAWAL_REQUEST = 'WITHDRAWAL_REQUEST';
export const WITHDRAWAL_SUCCESS = 'WITHDRAWAL_SUCCESS';
export const WITHDRAWAL_FAILURE = 'WITHDRAWAL_FAILURE';

// WITHDRAWAL PROCEED ACTION TYPES
export const WITHDRAWAL_PROCEED_REQUEST = 'WITHDRAWAL_PROCEED_REQUEST';
export const WITHDRAWAL_PROCEED_SUCCESS = 'WITHDRAWAL_PROCEED_SUCCESS';
export const WITHDRAWAL_PROCEED_FAILURE = 'WITHDRAWAL_PROCEED_FAILURE';

// GET WITHDRAWAL HISTORY ACTION TYPES
export const GET_WITHDRAWAL_HISTORY_REQUEST = 'GET_WITHDRAWAL_HISTORY_REQUEST';
export const GET_WITHDRAWAL_HISTORY_SUCCESS = 'GET_WITHDRAWAL_HISTORY_SUCCESS';
export const GET_WITHDRAWAL_HISTORY_FAILURE = 'GET_WITHDRAWAL_HISTORY_FAILURE';

// GET WITHDRAWAL REQUEST ACTION TYPES
export const GET_WITHDRAWAL_REQUEST_REQUEST = 'GET_WITHDRAWAL_REQUEST_REQUEST';
export const GET_WITHDRAWAL_REQUEST_SUCCESS = 'GET_WITHDRAWAL_REQUEST_SUCCESS';
export const GET_WITHDRAWAL_REQUEST_FAILURE = 'GET_WITHDRAWAL_REQUEST_FAILURE';

// PAYMENT DETAILS ACTION TYPES
export const ADD_PAYMENT_DETAILS_REQUEST = 'ADD_PAYMENT_DETAILS_REQUEST';
export const ADD_PAYMENT_DETAILS_SUCCESS = 'ADD_PAYMENT_DETAILS_SUCCESS';
export const ADD_PAYMENT_DETAILS_FAILURE = 'ADD_PAYMENT_DETAILS_FAILURE';

export const GET_PAYMENT_DETAILS_REQUEST = 'GET_PAYMENT_DETAILS_REQUEST';
export const GET_PAYMENT_DETAILS_SUCCESS = 'GET_PAYMENT_DETAILS_SUCCESS';
export const GET_PAYMENT_DETAILS_FAILURE = 'GET_PAYMENT_DETAILS_FAILURE';

export const DELETE_PAYMENT_DETAILS_REQUEST = 'DELETE_PAYMENT_DETAILS_REQUEST';
export const DELETE_PAYMENT_DETAILS_SUCCESS = 'DELETE_PAYMENT_DETAILS_SUCCESS';
export const DELETE_PAYMENT_DETAILS_FAILURE = 'DELETE_PAYMENT_DETAILS_FAILURE';